name: analysis
channels:
  - conda-forge
dependencies:
  - root
  - pip
  - uproot=4.3.7
  - awkward-pandas=2023.8.0
  - pandas=1.2.0
  - keras=2.13.1
  - np_utils
  - tensorflow=2.13.0
  - matplotlib
  - python=3.11.5
