name: analysis
channels:
  - conda-forge
dependencies:
  - root
  - pip
  - uproot
  - awkward-pandas=2023.8.0
  - pandas
  - keras
  - np_utils
  - tensorflow
  - matplotlib
  - protobuf=3.18.0
  - python=3.9.0
